### ISSUE TITLE
[Meta] Write document describing protocol requirements

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#1]
This issue will be used to track work items to author a consensus requirements document.  This will help guide discussion whether protocol features are in scope or out of scope, and to evaluate the suitability of technology choices.

The requirements flow primarily from three sources:
- [x] Requirements that come from the functions needed to implement the Presentation API [1] #2 
- [ ] Requirements that come from the functions needed to implement the Remote Playback API [2] #3 
- [x] Non-functional requirements: security, efficiency, usability. #4 

Starting points are the draft requirements for the community group recharter [3], along with the slide deck I presented at TPAC 2016.   I can simplify these and put them into a PR to start this work item.

[1] https://w3c.github.io/presentation-api/
[2] https://w3c.github.io/remote-playback/
[3] https://github.com/webscreens/cg-charter/blob/gh-pages/requirements.md

**Comment by louaybassbouss** [comment]
@mfoltzgoogle What do you think about considering "guest mode" (Allow users not in the same network to present on the screen) in the requirements?

**Comment by mfoltzgoogle** [comment]
@louaybassbouss Sorry for missing https://github.com/webscreens/openscreenprotocol/issues/1#issuecomment-273416257 earlier!

According to the charter for the community group [1], support for displays outside the controller's local area network is not in scope, so I don't think we can list guest mode as a requirement.

However I don't think it's a problem to hypothesize whether a given transport would be possible to use over a WAN without diving into a specific mechanism.  After all the protocol may be extended to support this case in the future outside the scope of the CG.

Filed Issue #41 for guest mode considerations.

[1] https://webscreens.github.io/cg-charter/

**Comment by louaybassbouss** [comment]
thx @mfoltzgoogle agree with you this out of scope. But now we have a new issue #41 for this we can discuss there if this is a relevant feature or not (low prio).

**Comment by mfoltzgoogle** [comment]
Closing out this old issue, discussion of Guest Mode can continue in #41.
