### ISSUE TITLE
[Remote Playback] Capabilities for HDR rendering and display

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#194]
This issue is tracking requirements to allow one agent to determine another's capabilities to render and display HDR media, both for streaming and remote playback.

At the Berlin F2F [1], it was noted that HDR capabilities are under discussion in the Media WG, and this issue is tracking the work being done there to align the protocol with the data model that will be used:

- [x] https://github.com/w3c/media-capabilities/issues/118: Add Support for Querying HDR Decode and Render Capabilities
- [x] https://github.com/w3c/media-capabilities/issues/119: Add Support for Querying HDR & 4K Video Display Capabilities

It looks likely that this topic will be on the agenda of the Media WG at TPAC 2019.

**Comment by mfoltzgoogle** [comment]
Ref: https://www.w3.org/2019/09/15-webscreens-minutes.html#x16

w3c/media-capabilities#118 has been closed, but w3c/media-capabilities#119 remains open.  I think it would make sense to land a PR to align with #118.

**Comment by anssiko** [comment]
>ACTION: @mfoltzgoogle to propose a PR to align OSP with Media Capabilities issue https://github.com/w3c/media-capabilities/issues/118

via https://www.w3.org/2020/10/20-webscreens-minutes.html#a04

**Comment by anssiko** [comment]
w3c/media-capabilities#119 was closed and spawned two issues:

- [ ] `Screen.video.hdrSupported` https://github.com/w3c/media-capabilities/issues/135
- [ ]  CSS length units in `video-*` media features https://github.com/w3c/csswg-drafts/issues/5044

**Comment by mfoltzgoogle** [comment]
It sounds like there wasn't an explicit action recorded in the last F2F minutes [1], but for the record, we discussed consulting with the Media WG folks working on Media Capabilities and related APIs to get feedback on PR #225, to resolve the first of these two issues (the render/decoding capabilities).

[1] https://www.w3.org/2021/02/23-webscreens-minutes.html#t02

**Comment by chrisn** [comment]
Please let me know if you'd like to bring this to a Media WG meeting, happy to put this on the agenda.

**Comment by anssiko** [comment]
@chrisn given https://github.com/w3c/media-capabilities/issues/135 and w3c/csswg-drafts#5044 haven't received attention recently I'd appreciate that. Please drop meeting logistics pointer to this issue so interested people can join.

**Comment by chrisn** [comment]
Meeting details are linked [here](https://www.w3.org/media-wg/). Upcoming dates are Tuesday 8 June at 14:00 UTC, 6 July at 21:00 UTC. Do you have any preference for date?

/cc @jernoble

**Comment by anssiko** [comment]
@mfoltzgoogle please note the upcoming Media WG meeting dates where this issue and its collateral are discussed. I think you may want to participate, and I suspect the latter 6 July at 21:00 UTC would be preferred by you (I may not be available at that time, but don't block on me).

**Comment by mfoltzgoogle** [comment]
Didn't see this before the June 8 meeting (sorry!) and July 6 is a Google holiday here in the US.  However I'll follow whatever the agenda the Media WG wishes on this item - whether that's July, August or later.

**Comment by chrisn** [comment]
Let's arrange for 11 January, given Mark's preferences.

**Comment by chrisn** [comment]
The joint meeting with the Media WG is confirmed for 11 January, here are the [meeting details](https://www.w3.org/events/meetings/ab178610-074a-4aa2-881e-1af902d3c409).

**Comment by chrisn** [comment]
The minutes from the joint meeting with Media WG are [here](https://www.w3.org/2022/01/11-mediawg-minutes.html#t01). Summary:

* We can refer to definitions in https://www.w3.org/TR/mediaqueries-5/ (display capabilities) and https://w3c.github.io/media-capabilities/#enumdef-colorgamut (decode capabilities)

* The definition for video plane resolution (as opposed to graphics plane resolution), for TV devices has not been settled in CSSWG. The latest issue is https://github.com/w3c/csswg-drafts/issues/6891

* Next step is to update PR https://github.com/w3c/openscreenprotocol/pull/225 and @chcunningham to offered to review

**Comment by mfoltzgoogle** [comment]
Relaying this comment from #225 so it can be addressed in a future PR:

> For MediaCapabilities, colorGamut is just one of 3 properties needed to support for a given flavor of HDR. The others are TransferFunction and HdrMetadataType. Do those make sense as additional parameters in this spec?

Yes they would, if they affect how the sender might want to encode media (or decide if a media stream was compatible with a receiver). I'd like to tackle that in a separate PR since conveying the HDR data over the wire could require additional changes to the protocol.

**Comment by mfoltzgoogle** [comment]
Would like to propose landing the PR #225 to address the specification of colorGamut and opening another issue to specify the other two pieces of metadata needed for HDR media transmission (TransferFunction and HdrMetadataType).

**Comment by mfoltzgoogle** [comment]
PR #225 was already landed (missed that earlier in this thread - oops.)

Since this GitHub issue is already referenced in the spec as Issue #16, rather than open a new issue, let's continue to use this one to cover adding TransferFunction and HdrMetadataType.  I believe the definitions in MediaCapabilities should be the default choice here, but need to verify the enum values correspond to the right attributes of HDR encoded media that would be sent over the wire.

From Media Capabilities:
- [`TransferFunction`](https://w3c.github.io/media-capabilities/#transferfunction)
- [`HdrMetadataType`](https://w3c.github.io/media-capabilities/#hdrmetadatatype)
