### ISSUE TITLE
[meta] Publish First Public Working Draft

### ISSUE THREAD

**Issue by anssiko** [w3c/openscreenprotocol#249]
>RESOLUTION: publish the Open Screen Protocol as First Public Working Draft

via https://www.w3.org/2020/10/20-webscreens-minutes.html#r01

@mfoltzgoogle please ping us in this issue when you have completed the editorial pass so that we can advance into publication. In my view, the spec as is already meets or exceeds the expectations for an FPWD, and an editorial pass is nice to have, not required. I did one quick pass and did not find major issues.

@tidoust's assistance will be needed in making the publication happen given this is a FPWD. Any subsequent WD publications we can automate.

Based on my assessment we meet the [W3C Process requirements to publish a (First Public) Working Draft](https://www.w3.org/2020/Process-20200915/#RecsWD):

- [x] should document outstanding issues, and parts of the document on which the Working Group does not have consensus, and
  - [Open GH issues](https://github.com/w3c/openscreenprotocol/issues) document any known outstanding issues
- [x] may request publication of a Working Draft even if its content is considered unstable and does not meet all Working Group requirements.

Per the group's [decision policy](https://www.w3.org/2014/secondscreen/charter-2020.html#decisions), we can publish earliest 28 October 2020.

**Comment by anssiko** [comment]
@mfoltzgoogle, do you still plan to do the editorial pass on the ED? As said, I feel the spec already exceed the FPWD expectations, so I don't think that is strictly needed. Let us know and we'll proceed accordingly.

@tidoust, can you please check the spec meets publication checks, validator and other checks needed? Thanks!

**Comment by anssiko** [comment]
Per [2021 Q1 virtual meeting discussion](https://www.w3.org/2021/02/23-webscreens-minutes.html#t02), we aim to address the following editorial issues before publication, or note them as open issues in the spec if addressing then needs more time:

- [ ] Make a required/default remote playback state table https://github.com/w3c/openscreenprotocol/issues/148
- [ ] Meaning of receives-audio and receives-video capabilities https://github.com/w3c/openscreenprotocol/issues/200
- [ ] Do agents need to support the Cookies extension https://github.com/w3c/openscreenprotocol/issues/219
- [ ] Determine if there is an advantage to session resumption outside of early data https://github.com/w3c/openscreenprotocol/issues/220
- [ ] mv value needs encoding specified https://github.com/w3c/openscreenprotocol/issues/239
- [ ] Use the same codec names as the media APIs https://github.com/w3c/openscreenprotocol/issues/233

Here's the [Call for Consensus mail](https://lists.w3.org/Archives/Public/public-secondscreen/2021Feb/0015.html) to acquire the group's approval for the publication plan.

We aim to publish the FPWD no earlier than 10 March 2021.

@mfoltzgoogle @tidoust please check the issue list is valid and fill in any possible gaps.

**Comment by mfoltzgoogle** [comment]
anssiko@, I do not plan to resolve #233 before publishing the FPWD, as it would benefit from consultation with folks working on related APIs (e.g. Media Capabilities) in the Media WG.

**Comment by anssiko** [comment]
@mfoltzgoogle thanks for the review. Let’s note that open issue in the spec with the expectation Media WG will be consulted.

**Comment by anssiko** [comment]
We seem to be almost done with FPWD blockers thanks to swift updates by @mfoltzgoogle.

The remaining issues are #148 and #233.

@mfoltzgoogle feel free to close issues #219 #220 #239 if they're addressed.

**Comment by mfoltzgoogle** [comment]
We also discussed updating and landing the explainer (#168) to assist outside groups from reviewing the spec with sufficient context.  I plan to take that on after closing out the checklist above.

**Comment by anssiko** [comment]
Yes, landing the explainer with the FPWD would be nice to have. One convention is to put a link to the explainer into the header metadata to help discovery. Something like:

`!Explainer: <a href="https://github.com/w3c/openscreenprotocol/blob/master/explainer.md">Open Screen Protocol Explainer</a> `

**Comment by anssiko** [comment]
With PR #268 linking the spec to #233, we seem to tick all the boxes now. Thanks @mfoltzgoogle!

@tidoust can you work with @mfoltzgoogle to stage the spec for FPWD release no earlier than 10 March 2021, as noted in the [CfC](https://lists.w3.org/Archives/Public/public-secondscreen/2021Feb/0015.html)?

**Comment by tidoust** [comment]
@mfoltzgoogle What about the explainer (#168)? Are you planning to update and merge it in the next few days or should we go ahead without it?

**Comment by mfoltzgoogle** [comment]
If you can give me to the end of the week - if it's not done by then go ahead :-)

**Comment by tidoust** [comment]
> @tidoust to confirm.

I confirm!

**Comment by anssiko** [comment]
✅ FPWD transition request approved: https://github.com/w3c/transitions/issues/322

Non-blocking https://github.com/w3c/openscreenprotocol/pull/248 to be integrated into the FPWD if merged by Thursday 18 March.

**Comment by tidoust** [comment]
> if merged by Thursday 18 March.

Merging before Thursday, please :)

**Comment by mfoltzgoogle** [comment]
I merged the current snapshot of PR #248 so it can be incorporated into the FPWD.

**Comment by tidoust** [comment]
Achievement unlocked :)

First Public Working Draft published today at:
https://www.w3.org/TR/openscreenprotocol/
