### ISSUE TITLE
[Meta] Performance data for discovery protocols

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#69]
This meta-issue tracks the work to gather performance data on proposed discovery protocols.

Even though both SSDP and mDNS have been implemented in Chrome (and Mozilla?), for a variety of reasons, it can be tricky to use data from the field to compare performance of the discovery protocols themselves.  Therefore I propose running some experiments to gather accurate data.

- [x] Design experimental framework: what devices, what network, what software and what measurements.
- mDNS
  - [x] Issue #37: [mDNS] Get reliability data
  - [ ] Issue #38: [mDNS] Get network and power efficiency data
- SSDP
  - [x] Issue #68: [SSDP] Get reliability data
  - [ ] Issue #26: [SSDP] Get network and power efficiency data
- [ ] Collect data on latency of discovery (when devices enter/leave the LAN)

Separately from experiments, there may be some data we can share from Chrome internal metrics related to reliability.  I will look into it and report back.

**Comment by louaybassbouss** [comment]
Maybe we can use these libraries to do some experiments:

-  [mdns](https://www.npmjs.com/package/mdns): A Node.js module the can be used to advertise and discover services. I think it uses Bonjour.
- [peer-ssdp](https://www.npmjs.com/package/peer-ssdp): A Node.js module provided by Fraunhofer FOKUS which implements the SSDP protocol (without UPnP).

**Comment by mfoltzgoogle** [comment]
Based on TPAC discussion I'll take an action to share data on the success of SSDP and mDNS "in the field" and in particular how often one succeeds when the other fails.   If we break this down by platform, we can guess how often it is a device specific issue versus a networking issue.

**Comment by mfoltzgoogle** [comment]
At the Berlin F2F I shared reliability data for SSDP and mDNS, and based on that we resolved to make mDNS mandatory for controllers and receivers, and make SSDP a non-mandatory alternative.

The issues to get networking and power benchmarking remain open, so leaving this meta-issue open.   It's possible additional data from benchmarking may change the tradeoffs here.

**Comment by mfoltzgoogle** [comment]
We've already committed to mDNS in the current spec.
