### ISSUE TITLE
[meta] Performance data for transport protocols

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#74]
This meta-issue tracks the work to gather performance data on proposed trasnport protocols.

- [x] Design experimental framework: what devices, what network, what software and what measurements.
- [ ] QUIC
  - [ ] Issue #63: [QUIC] Get reliability data
  - [ ] Issue #65: [QUIC] Get data on network and power efficiency 
  - [ ] Issue #66: [QUIC] Get data on connection and message latency
- [ ] RTC DataChannel
  - [ ] Issue #30: [DataChannel] Get reliability data
  - [ ] Issue #33: [DataChannel] Obtain data on network and power efficiency
  - [ ] Issue #31: [DataChannel] Get data on connection and message latency
