### ISSUE TITLE
[Meta] Open Screen Protocol 1.0 Specification

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#98]
This meta-issue tracks the work required to complete the 1.0 specification, outlined in PR #97.

- [x] Second Screen Community Group boilerplate (custom or as part of Bikeshed repo)
- [x] Issue #99: Complete requirements and terminology sections
- [x] Issue #100: Incorporate material from [mdns.md](mdns.md)
- [x] Issue #101: Incorporate material from [quic.md](quic.md)
- [x] Issue #102: Incorporate material from [j-pake.md](j-pake.md)
- [x] Issue #77: CBOR-based Presentation API protocol
- [x] Issue #12: Remote Playback API protocol
- [x] Issue #13: Security and Privacy section

**Comment by mfoltzgoogle** [comment]
With the closing of Issue #12 we've completed the first draft of the 1.0 protocol.  I believe it should meet the (functional requirements)[requirements.md] laid out for Presentation API.  We didn't finish requirements for Remote Playback API, but we should do that (Issue #3).

Over the course of drafting the 1.0 spec, there were about 25 issues opened relevant to the spec itself.

What I propose (in this order).
1. Resolve Issue #3 by adding requirements for Remote Playback.
2. Verify that the spec as-is meets the functional requirements of the APIs and relevant non-functional requirements.
3. Close this issue.
4. Tag additional issues with "v1-spec" if they are relevant to producing a more mature spec for wider review.  I imagine some of these we will want to discuss at the F2F.

Let me know if this plan sounds good @louaybassbouss @anssiko @tidoust @chrisn  (and other contributors).

**Comment by anssiko** [comment]
Thank you for your efforts and congrats for reaching this significant milestone. The proposed plan sounds good. F2F is a fine opportunity to review and discuss additional issues.
